name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write

jobs:
  build:
     runs-on: ubuntu-latest
     env:
      OIDC_AUDIENCE: 'jfrog-oidc'
      OIDC_PROVIDER: 'alex-github'
      PLATFORM_REPO: 'alex-libs-release'
     defaults:
      run:
        working-directory: ./package
     steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:  
          JF_URL: ${{ env.JF_URL }}
        with:
          oidc-provider-name: ${{ env.OIDC_PROVIDER }}
          oidc-audience: ${{ env.OIDC_AUDIENCE }}

      - name: Set CLI Config
        run: jf mvnc --global=true --repo-resolve=$PLATFORM_REPO --repo-deploy=$PLATFORM_REPO
          
      - name: Install Dependencies
        run: jf mvn install
           
